NAME: 'resnet50.base.adam'

DATASET:
  TYPE: 'pedes'
  NAME: 'PA100k'
  TRAIN_SPLIT: 'trainval'
  VAL_SPLIT: 'test'
  ZERO_SHOT: False
  LABEL: 'prior'
  HEIGHT: 256
  WIDTH: 192

RELOAD:
  TYPE: False
  NAME: 'backbone'
#  PTH: 'ckpt_max_2024-06-30_13:38:09.pth'

BACKBONE:
  TYPE: 'resnet50'
#  TYPE: 'bninception'
#  TYPE: 'tresnetM'
#  TYPE: 'swin_s'
#  TYPE: 'vit_s'
#  TYPE: 'vit_b'

CLASSIFIER:
#  NAME: 'linear'
  NAME: 'SSPNet'
  POOLING: 'avg'
  SCALE: 1
  BN: False

LOSS:
  TYPE: 'bceloss'
  LOSS_WEIGHT: [1]
  SAMPLE_WEIGHT: 'weight'


TRAIN:
  CLIP_GRAD: True
  BATCH_SIZE: 50
  MAX_EPOCH: 100
  OPTIMIZER:
    TYPE: 'adam'
    WEIGHT_DECAY: 5e-4
  LR_SCHEDULER:
    TYPE: 'plateau'
    LR_FT: 0.0001
    LR_NEW: 0.0001
  EMA:
    ENABLE: True

METRIC:
  TYPE: 'pedestrian'

VIS:
  CAM: 'valid'
